import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Flex, Text } from "@chakra-ui/react";
import icon from "../../public/icon.png";
import item from "../../public/item.png";
import shelf from "../../public/shelf.png";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       */}
      <Flex flexDir={"column"} alignItems={"center"} p={"40px"}>
        <Box w={"440px"}>
          <Image src={icon} />
        </Box>
        <Text
          fontSize={32}
          fontWeight={700}
          marginTop={"40px"}
          marginBottom={"40px"}
        >
          Smart Warehouse Rack Management System
        </Text>
        <Flex
          borderRadius={"20px"}
          p={"40px"}
          paddingX={"100px"}
          bg={"rgba(217, 217, 217, 0.37)"}
          gap={"60px"}
        >
          <Flex
            cursor={"pointer"}
            flexDir={"column"}
            alignItems={"center"}
            onClick={() => router.push("/packets-inventory")}
          >
            <Flex
              w={"180px"}
              h={"180px"}
              borderRadius={"100px"}
              bg={"linear-gradient(180deg, #FFE600 0%, #FFC30D 44.79%);"}
              alignItems={"center"}
              justifyContent={"center"}
            >
              <Box width={"100px"}>
                <Image src={item} />
              </Box>
            </Flex>
            <Text fontSize={32} fontWeight={700} marginTop={"20px"}>
              Packets Inventory
            </Text>
          </Flex>

          <Flex
            flexDir={"column"}
            alignItems={"center"}
            cursor={"pointer"}
            onClick={() => router.push("/shelf")}
          >
            <Flex
              w={"180px"}
              h={"180px"}
              borderRadius={"100px"}
              bg={"linear-gradient(180deg, #FFE600 0%, #FFC30D 44.79%);"}
              alignItems={"center"}
              justifyContent={"center"}
            >
              <Box width={"100px"}>
                <Image src={shelf} />
              </Box>
            </Flex>
            <Text fontSize={32} fontWeight={700} marginTop={"20px"}>
              Shelf
            </Text>
          </Flex>
        </Flex>
      </Flex>
    </>
  );
}
